___

<a href='https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# NumPy Ejercicios

Ahora que hemos aprendido sobre NumPy, probemos los conocimientos. Comenzaremos con algunas tareas simples y luego se harán algunas preguntas más complicadas.

#### Importar NumPy como np

In [2]:
import numpy as np

#### Crear un array de 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un array de 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un array de 10 cincos

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un array de enteros desde 10 a 50

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Cree una matriz de todos los enteros pares del 10 al 50

In [10]:
np.arange(10,51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Cree una matriz de 3x3 con valores que van de 0 a 8

In [14]:
matrix = np.array(([0,1,2],[3,4,5],[6,7,8]))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz de identidad de 3x3

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy para generar un número aleatorio entre 0 y 1

In [18]:
np.random.rand(1)

array([0.4398954])

#### Utilice NumPy para generar una matriz de 25 números aleatorios muestreados a partir de una distribución normal estándar

In [21]:
np.random.randn(5,5)

array([[ 0.32948357,  2.81749152,  0.52031039,  0.28514682, -1.50327974],
       [ 1.42151986, -0.36634252, -0.83711498, -1.11350196,  0.01338258],
       [ 1.69658384,  0.46011365, -0.91934687, -1.20044173, -1.80424336],
       [ 1.84041736, -0.04833697,  1.38289586,  0.62809359,  1.50176773],
       [-0.19585858, -0.30818261,  1.05632302,  1.40795486, -0.40997326]])

#### Cree la siguiente matriz:

In [28]:
np.arange(0.01,1.01, 0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Cree una matriz de 20 puntos espaciados linealmente entre 0 y 1:

In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexación y Selección

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS

In [49]:
arr = mat[2:5, 1:5]
arr

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS

In [52]:
mat[3,4]

20

In [ ]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS

In [65]:
arr2 = mat[:3, 1:2]
arr2

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS

In [71]:
arr3 = mat[4:5]
arr3

array([[21, 22, 23, 24, 25]])

In [ ]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS

In [73]:
arr4 = mat[3:5]
arr4

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Ahora hacer lo siguiente

#### Obtenga la suma de todos los valores en mat

In [75]:
np.sum(mat)

325

#### Obtenga la desviación estándar de los valores en mat




In [77]:
np.std(mat)

7.211102550927978

#### Obtenga la suma de todas las columnas en mat

In [79]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Buen trabajo!